name = "EasyTranspose"
uuid = "414d4a1f-53a7-59c9-88e8-37580f05eeca"
authors = ["Mus <mus-m@outlook.com>"]
version = "0.1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
